name: streaming_forms
description: A form package providing Dart streams.
version: 0.2.0-alpha.1
homepage: https://github.com/erayerdin/streaming_forms
repository: https://github.com/erayerdin/streaming_forms
issue_tracker: https://github.com/erayerdin/forms/issues
platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:
topics:
  - widgets
  - ui

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^5.0.0
